name: MacOS
on: 
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          # 6.9.1
          - qt_version: 6.9.1
            qt_arch: clang_64
            # arch: x64
            modules: 'qthttpserver qtwebsockets qtmultimedia'
    
    env:
      Repository_Name: 'QListenTogether'
      BUILD_TYPE: Release
      BUILD_PATH: build
      assume: --release
      qt_target: 'desktop'
      qt_host: 'mac'
      archiveName: 'QListenTogether-${{ matrix.qt_version }}-${{ matrix.qt_arch }}'
    steps: 
      # 安装Qt
      - name: Install Qt
        if: 'true'
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          host: ${{ env.qt_host }}
          target: ${{ env.qt_target }}
          arch: ${{ matrix.qt_arch }}
          install-deps: 'true'
          cache: 'true'
          aqtversion: '==3.1.*'
          modules: ${{ matrix.modules }}
          # tools: ${{ matrix.tools }}
      # 拉取代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: CMake Build
        id: build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }} -B ${{ env.BUILD_PATH }}
          ls
      # CMake Install
      - name: CMake Install
        env:
          prefix: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}
          cmake --build ${{ env.BUILD_PATH }} --target install --config ${{ env.BUILD_TYPE }} -j
          ls
      # 上传artifacts          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.archiveName }}
          path: ${{ github.workspace }}/${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }}/${{ env.Repository_Name }}.app
      # 打包
      - name: package
        run: |
          # 拷贝依赖
          macdeployqt ${{ github.workspace }}/${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }}/${{ env.Repository_Name }}.app -qmldir=. -verbose=1 -dmg
          ls
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }}/${{ env.Repository_Name }}.dmg
          asset_name: ${{ env.archiveName }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
